name: seguro_app
description: "App para gerencimaneto de seguros."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.4.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  webview_flutter: ^4.13.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.9.0
  flutter_triple: ^3.0.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
